# echo-demo Service 
apiVersion: v1
kind: Service
metadata:
  name: hub-svc-echo-demo
  labels:
    whatCat: hub-my-echo-demo
spec:
  type: NodePort
  ports:
  - nodePort: 31080
    port: 8080
    protocol: TCP
  selector:
    whatCat: hub-my-echo-demo